name: "add10"
backend: "python"

input [
  {
    name: "INPUT"
    data_type: TYPE_FP64
    dims: [ 1 ]
  }
]
output [
  {
    name: "sum"
    data_type: TYPE_FP64
    dims: [ 1 ]
  }
]

instance_group [{ kind: KIND_CPU }]
